name: Linux

on:
  push:
    branches: [ master, '*-ci' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build_linux:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}

    - name: Install Mosquitto library
      run: sudo apt-get install mosquitto

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install paho-mqtt==1.6.1
        python -m pip install zserio
        python -m pip install astroid==2.15.0
        python -m pip install pylint==2.16.3
        python -m pip install mypy==0.931

    - name: Build Zserio Python Pub/Sub Paho Mqtt
      run: |
        zserio -src examples/calculator calculator.zs -python build/gen
        mypy build/gen examples/calculator src
        PYTHONPATH=build/gen pylint examples src \
              --disable=missing-module-docstring,missing-function-docstring,duplicate-code,too-many-arguments \
              --disable=too-few-public-methods,broad-exception-caught,unnecessary-lambda-assignment

    - name: Test Zserio Python Pub/Sub Paho Mqtt
      run: |
        cd examples/calculator
        python power_of_two_provider.py &
        python square_root_of_provider.py &
        sleep 10
        echo -e "p\\n100\\nq" | python calculator_client.py | grep "square_root_of: 10.0"
        echo -e "s\\n100\\nq" | python calculator_client.py | grep "power_of_two: 10000"
        kill $(jobs -p)
      env:
        PYTHONDONTWRITEBYTECODE: 1
        PYTHONPATH: "../../src:../../build/gen"
